name: hyperhire_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  banners: ^0.0.1
  core: ^0.0.1
  ui: ^0.0.1
  products: ^0.0.1
  reviews: ^0.0.1
  users: ^0.0.1
  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  injectable: ^2.5.0
  databases: ^0.0.1
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true