name: hyperhire_workspace
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

workspace: 
 - packages/core

dependencies:
  dartz: ^0.10.1
  
dev_dependencies:
  melos: ^6.3.2
  flutter_lints: ^5.0.0
