name: banners
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  core: ^0.0.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  kt_dart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/